---
- name: install epel
  yum:
    name: 'epel-release'
    state: installed
  become: true

- name: install common packages
  yum:
    name: '{{ item }}'
    state: installed
  become: true
  with_items:
  - 'nfs-utils'
  - 'policycoreutils-python'
  - 'python2-pip'

#- name: upgrade pip
#  command: pip install setuptools --upgrade
#  become: true

#- name: get get-pip.py
#  copy:
#    src: get-pip.py
#    dest: /tmp/get-pip.py
#- name: run get-pip.py
#  command: python /tmp/get-pip.py
#  become: true

