---
- hosts: db
  tasks:
  - name: Stop the MongoDB database
    systemd:
      name: mongod
      state: stopped
  - name: Unmount the database volume
    mount:
      path: /var/lib/mongodb
      state: unmounted
  - name: Detach volume from server
    os_server_volume: 
      state: absent
      cloud: mycloud
      server: db0
      volume: dbvol
    delegate_to: localhost
  - name: Restore Cinder backup volume
    shell: "source /root/keystonerc_demo && openstack volume backup restore dbvol_backup dbvol"
    delegate_to: localhost
    register: vol_restore
    failed_when:
    - vol_restore.rc > 0
    - "'VolumeBackupsRestore' not in vol_restore.stderr"
  - name: Wait for the restore of the database volume
    shell: "source /root/keystonerc_demo && openstack volume show -c status -f value dbvol"
    register: restore_progress
    until: restore_progress.stdout is search("available")
    retries: 60
    delay: 5
    delegate_to: localhost
  - name: Reattach volume to the database server
    os_server_volume: 
      state: present
      cloud: mycloud
      server: db0
      volume: dbvol
      device: /dev/vdb
    delegate_to: localhost
  - name: Mount the database volume
    mount:
      path: /var/lib/mongodb
      state: mounted
      src: LABEL=dbvol
      fstype: xfs
  - name: Start the MongoDB database
    systemd:
      name: mongod
      state: started
...
