---
- name: delete the load balancer
  gather_facts: false
  hosts: localhost
  tasks:
  - name: 'UNDO: create load balancer and listener'
    os_loadbalancer:
      name: weblb
      state: absent
      vip_network: public
      vip_subnet: '{{ osp_admin_subnet.name }}'
...
