---
- name: delete the web app stack
  gather_facts: false
  hosts: localhost
  tasks:
  - name: 'UNDO: delete the sql server'
    os_server:
      name: db0
      state: absent
  - name: 'UNDO: delete DB volume in cinder'
    os_volume:
      display_name: dbvol
      state: absent
  - name: 'UNDO: delete the web server'
    os_server:
      name: web{{ item }}
      state: absent
    with_sequence: start=0 end=1
...
