---
- name: Stop the MongoDB database
  systemd:
    name: "{{ service_name }}"
    state: stopped
  become: true
- name: Unmount the database volume
  mount:
    path: "{{ db_vol_path }}"
    state: unmounted
  become: true
- name: Detach volume from server
  os_server_volume: 
    state: absent
    server: "{{ inventory_hostname_short }}"
    volume: "{{ volume_name }}"
  delegate_to: localhost
...
