---
- name:  set selinux context
  sefcontext:
    target: '{{ build_dir }}/glog/src(/.*)?'
    setype: httpd_sys_content_t
    state: present
  become: true

- name: apply context
  command: /usr/sbin/restorecon -Rv {{ build_dir }}/glog/src/
  become: true
