---
- name: allow for small files with mongo
  copy:
    dest: /etc/sysconfig/mongod
    content: |
      OPTIONS="--quiet -f /etc/mongod.conf --smallfiles"
  become: true
- name: copy conf file
  copy:
    src: mongod.conf
    dest: /etc/mongod.conf
  become: true
  notify:
  - restart mongod
- meta: flush_handlers
- name: copy mongo user add script
  copy:
    content: |
      db.createUser(
        { 
          user: "glog",
          pwd: "gl0g",
          roles: [ "readWrite", "dbAdmin"]
        }
      )
    dest: /root/glog_user.js
  become: true
- name: add glog user
  command: mongo glog ~/glog_user.js
  become: true
  ignore_errors: true
- name: sync backup dir
  synchronize:
    src: db-backup
    dest: '/srv/'
  become: true
- name: restore backup
  command: mongorestore '/srv/db-backup/glog'
  become: true
