---
- name: copy conf file
  copy:
    src: mongod.conf
    dest: /etc/mongod.conf
  become: true
  notify:
  - restart mongod
- name: start and enable mongod
  service:
    name: mongod
    state: restarted
    enabled: true
  become: true
- name: copy mongo user add script
  copy:
    content: |
      db.createUser(
        { 
          user: "glog",
          pwd: "gl0g",
          roles: [ "readWrite", "dbAdmin"]
        }
      )
    dest: /root/glog_user.js
  become: true
- name: add glog user
  command: mongo glog ~/glog_user.js
  become: true
  ignore_errors: true
- name: sync backup dir
  synchronize:
    src: db-backup
    dest: '/srv/'
  become: true
- name: restore backup
  command: mongorestore '/srv/db-backup/glog'
  become: true

#  shell: echo db.createUser({user: "glog",pwd: "gl0g",roles: [ "readWrite", "dbAdmin"]}) | mongo glog
#  mongodb_user:
#    database: 'glog'
#    name: 'glog'
#    password: 'gl0g'
#    state: present

#- name: firewall rules for mongo
#  firewalld:
#    port: 27017/tcp
#    permanent: true
#    state: enabled
#  notify:
#  - reload firewalld
#  become: true

#- name: restore backup database
#  command: scl enable rh-mongodb32 'mongorestore -d glog {{ glog_mnt }}/backup/glog'
#  become: true
#  when:
#  - restore|default('false') == 'true'
#  tags:
#  - dbrestore

