---
- name: Backing up the database via the Cinder service
  hosts: db
  tasks:
  - name: Check for an existing backup
    command: "openstack volume backup list -c Name -f value"
    register: backup_list
    delegate_to: localhost
  - debug: var=backup_list
  - name: Delete the existing cinder backup
    command: "openstack volume backup delete dbvol_backup"
    when: backup_list.stdout is search("dbvol_backup")
    delegate_to: localhost
  - name: Stop the database
    systemd:
      name: mongod
      state: stopped
    become: true
  - name: Create a Cinder Backup of Database Volume
    command: "openstack volume backup create --force --name dbvol_backup dbvol"
    delegate_to: localhost
  - name: Wait for backup to complete and then run the openstack volume backup list command
    command: "openstack volume backup list"
    register: output
    until: output.stdout is search("available")
    retries: 20
    delay: 5
    delegate_to: localhost
  - name: Start the database
    systemd:
      name: mongod
      state: started
    become: true

  - debug: var=output.stdout_lines
...
